#!/bin/sh
# Compare the package set about to be deployed against the one already
# published, and refuse to deploy a smaller one.
#
# This is the last gate before deploy-pages replaces the live repository.
# A Pages deployment is a whole-site replace, so a build that produces fewer
# packages than are already published silently destroys the difference --
# which is how a run that committed a single package came to overwrite the
# repository. collect-packages.sh only establishes that *something* was
# built; only a comparison against the live site can tell a full rebuild
# from a near-total loss.
#
# Required environment variables:
#   BASE_URL - public root of the published repository
#
# Optional:
#   ALLOW_PACKAGE_DROP - set to "true" to permit a smaller set, for when a
#                        port is deliberately dropped from config/pkglist.

set -eu

: "${BASE_URL:?BASE_URL must be set}"
ALLOW_PACKAGE_DROP="${ALLOW_PACKAGE_DROP:-false}"

status=0

for abi_dir in _site/FreeBSD:*:*; do
    [ -d "$abi_dir" ] || continue
    abi=$(basename "$abi_dir")

    new_count=$(find "$abi_dir/All" -name '*.pkg' -type f 2>/dev/null | wc -l | tr -d ' ')

    # Count .pkg links in the published directory index. The index is
    # generated by generate-directory-indexes.sh, so its shape is ours to
    # rely on. A missing or unreachable index counts as zero: a first
    # deployment has nothing to lose, and a fetch failure must not be able
    # to block an otherwise good deploy.
    live_index=$(curl -sSfL --retry 3 --retry-delay 2 \
        "$BASE_URL/$abi/All/" 2>/dev/null) || live_index=''
    live_count=$(printf '%s' "$live_index" \
        | grep -oE 'href="[^"]*\.pkg"' | wc -l | tr -d ' ')

    echo "$abi: deploying $new_count package(s), $live_count currently published"

    if [ "$new_count" -ge "$live_count" ]; then
        continue
    fi

    lost=$(( live_count - new_count ))
    if [ "$ALLOW_PACKAGE_DROP" = "true" ]; then
        echo "  dropping $lost package(s); allowed by ALLOW_PACKAGE_DROP" >&2
        continue
    fi

    echo "  ERROR: this deploy would remove $lost package(s) from $abi." >&2
    echo "  Re-run the build, or dispatch with allow_package_drop if the" >&2
    echo "  reduction is intended (a port left config/pkglist)." >&2
    status=1
done

exit "$status"
